Repository needone/pr-tricks, pull requests merged in 2021-05, with the labels that each got.

#32 feature(#25): Create default workflow
  .github/workflows/default.yml
Labels: ci

#35 Feature#23/Pouvoir charger une trickList externe à partir d'une URL
  .vscode/settings.json
  option.css.map
  package-lock.json
  package.json
  public/manifest.json
  public/styles/options.css
  public/styles/options.css.map
  public/styles/options.scss
  public/views/options.html
  src/data/test.json
  src/github-review-script.ts
  src/trick-list-options.ts
  src/types/chrome-storage.type.ts
  src/utils/is-tricks.utils.ts
  src/utils/request.utils.ts
Labels: api, enhancement, front

#37 Bug(#36): Bug lors de la réinitialisation des données
  public/views/options.html
  src/trick-list-options.ts
Labels: bug

#40 Fix/#39 Bug on tricks highlight
  public/manifest.json
  src/data/trick-list.ts
  src/github-review-script.ts
Labels: api, bug

#42 Feature/#6 Control import trick list for projects
  package-lock.json
  package.json
  public/styles/options.css
  public/styles/options.css.map
  public/styles/options.scss
  public/views/options.html
  src/data/trick-list.ts
  src/github-review-script.ts
  src/trick-list-options.ts
  src/types/chrome-storage.type.ts
  src/types/external-tricks.type.ts
  src/types/url-tricks.type.ts
Labels: api, enhancement, front

#43 Fix/#33: Extension now auto-initialize
  public.pem
  public/styles/options..map
  public/styles/options.css
  public/styles/options.scss
  public/views/options.html
  src/trick-list-options.ts
Labels: api, bug, front
